
spring:
  application:
    name: eurekaserver
eureka:
  instance:
    hostname:
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false

server:
  port: 8761


