spring:
  application:
    name: phonebook
  sql:
    init:
      mode: always
      continue-on-error: true

  # Spring JPA configuration
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
    show-sql: true

  # Datasource Configuration
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/orclpdb1
    username: atael
    password: Welcome1234##
    driver-class-name: oracle.jdbc.OracleDriver
    type: oracle.ucp.jdbc.PoolDataSource
    oracleucp:
      connection-factory-class-name: oracle.jdbc.pool.OracleDataSource
      connection-pool-name: phoneBookConnectionPool
      initial-pool-size: 15
      min-pool-size: 10
      max-pool-size: 30
      fast-connection-failover-enabled: false

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
    enabled: true
